# Generated by Django 4.2 on 2023-06-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_user_alter_profile_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="media/profile_pics/default_profile_picture.png",
                null=True,
                upload_to="media/profile_pics/",
            ),
        ),
    ]
