# Generated by Django 4.2 on 2023-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
