# Generated by Django 4.1.4 on 2023-01-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_auther', to='participants.participant')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_idea', to='ideas.idea')),
            ],
        ),
    ]
