# Generated by Django 4.1.4 on 2023-01-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('url', models.URLField()),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_auther', to='participants.participant')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_campaign', to='campaigns.campaign')),
            ],
        ),
    ]
