# Generated by Django 4.1.4 on 2023-01-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='url',
            field=models.URLField(default=0.0004945598417408506),
            preserve_default=False,
        ),
    ]
