# Generated by Django 4.2 on 2023-05-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="idea",
            old_name="created_at",
            new_name="idea_created_at",
        ),
        migrations.RenameField(
            model_name="idea",
            old_name="updated_at",
            new_name="idea_updated_at",
        ),
    ]
