# Generated by Django 4.1.4 on 2023-01-20 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idea",
            name="auther",
        ),
        migrations.AddField(
            model_name="idea",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="idea_create",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="idea",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="idea_update",
                to=settings.AUTH_USER_MODEL,
                verbose_name="last updated by",
            ),
        ),
    ]
