# Generated by Django 4.1.4 on 2023-01-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_merge_20230120_1237"),
        ("ideas", "0002_remove_idea_auther_idea_author_idea_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idea_campaign",
                to="campaigns.campaign",
            ),
        ),
    ]
