# Generated by Django 4.2 on 2023-05-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0002_rename_created_at_idea_idea_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="idea",
            old_name="likes",
            new_name="idea_likes",
        ),
    ]
