# Generated by Django 4.1.4 on 2023-01-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_merge_20230120_1237"),
        ("ideas", "0003_alter_idea_campaign"),
    ]

    operations = [
        migrations.RenameField(
            model_name="idea",
            old_name="description",
            new_name="idea_description",
        ),
        migrations.RenameField(
            model_name="idea",
            old_name="title",
            new_name="idea_title",
        ),
        migrations.RenameField(
            model_name="idea",
            old_name="url",
            new_name="idea_url",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="author",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="id",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="idea",
            name="campaign_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="campaigns.campaign",
            ),
            preserve_default=False,
        ),
    ]
