# Generated by Django 4.2 on 2023-06-16 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ideas", "0004_idea_idea_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="idea_favorites",
            field=models.ManyToManyField(
                related_name="favorite_ideas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
