# Generated by Django 4.2 on 2023-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0005_idea_idea_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="idea_status",
            field=models.CharField(
                choices=[
                    ("IDEATION", "Ideation"),
                    ("INREVIEW", "In Review"),
                    ("CLOSED", "Closed"),
                    ("POC", "Poc"),
                    ("INCUBATION", "Incubation"),
                ],
                default="IDEATION",
                max_length=10,
            ),
        ),
    ]
