# Generated by Django 4.1.4 on 2023-01-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0006_idea_campaign_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idea",
            name="campaign_id",
        ),
    ]
