# Generated by Django 4.1.4 on 2023-01-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0007_remove_idea_campaign_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="campaign_id",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
