# Generated by Django 4.1.4 on 2023-01-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0008_idea_campaign_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="campaign_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
