# Generated by Django 4.1.4 on 2023-01-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0010_alter_idea_campaign_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idea",
            name="campaign_id",
        ),
        migrations.AddField(
            model_name="idea",
            name="campaign_id_elias",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
