# Generated by Django 4.1.4 on 2023-01-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0011_remove_idea_campaign_id_idea_campaign_id_elias"),
    ]

    operations = [
        migrations.RenameField(
            model_name="idea",
            old_name="campaign_id_elias",
            new_name="campaign_id",
        ),
    ]
