# Generated by Django 4.1.4 on 2023-01-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0014_idea_likes_idealike"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="background",
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="idea",
            name="impact",
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="idea",
            name="solution",
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="idea",
            name="team",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
