# Generated by Django 4.1.4 on 2023-01-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0015_idea_background_idea_impact_idea_solution_idea_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idea",
            name="idea_description",
        ),
    ]
