# Generated by Django 4.2 on 2023-04-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_campaigns', models.ManyToManyField(related_name='liked_campaigns', to='campaigns.campaign')),
                ('liked_comments', models.ManyToManyField(related_name='liked_comments', to='campaigns.campaign')),
                ('liked_ideas', models.ManyToManyField(related_name='liked_ideas', to='campaigns.campaign')),
            ],
        ),
    ]
