# Generated by Django 4.1.4 on 2023-01-17 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaigns', models.ManyToManyField(to='campaigns.campaign')),
                ('liked_campaigns', models.ManyToManyField(related_name='liked_campaigns', to='campaigns.campaign')),
                ('liked_comments', models.ManyToManyField(related_name='liked_comments', to='campaigns.campaign')),
                ('liked_ideas', models.ManyToManyField(related_name='liked_ideas', to='campaigns.campaign')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
