# Generated by Django 4.1.4 on 2023-01-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_campaign_token"),
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="liked_campaigns",
            field=models.ManyToManyField(
                related_name="liked_campaigns", to="campaigns.campaign"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="liked_comments",
            field=models.ManyToManyField(
                related_name="liked_comments", to="campaigns.campaign"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="liked_ideas",
            field=models.ManyToManyField(
                related_name="liked_ideas", to="campaigns.campaign"
            ),
        ),
    ]
