# Generated by Django 4.1.4 on 2023-01-03 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=250)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("image", models.ImageField(upload_to="")),
                (
                    "auther",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_auther",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
