# Generated by Django 4.1.4 on 2022-12-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant_Name', models.CharField(max_length=50)),
                ('Participant_BirthDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='Participants',
            field=models.ManyToManyField(to='campaigns.participant'),
        ),
    ]
