# Generated by Django 4.1.4 on 2023-01-20 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0002_remove_campaign_auther_campaign_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="manager",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_manager",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
