# Generated by Django 4.2 on 2023-06-15 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0002_campaign_campaign_opened"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorite_campaigns", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
