# Generated by Django 4.1.4 on 2022-12-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_participant_campaign_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="Participants",
        ),
        migrations.AddField(
            model_name="campaign",
            name="participants",
            field=models.ManyToManyField(to="campaigns.participant"),
        ),
    ]
