# Generated by Django 4.1.4 on 2022-12-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_remove_campaign_participants_campaign_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="participants",
        ),
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
