# Generated by Django 4.1.4 on 2023-01-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_participants_participant'),
        ('campaigns', '0003_campaign_manager'),
    ]

    operations = [
    ]
