# Generated by Django 4.1.4 on 2023-01-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_alter_campaign_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="token",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
